# Generated by Django 2.2.3 on 2019-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/static/image/default.png', null=True, upload_to='head_img/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(max_length=255, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_keep_play',
            field=models.BooleanField(null=True, verbose_name='是否是陪玩'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_singer',
            field=models.BooleanField(null=True, verbose_name='是否是卖唱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jx3_name',
            field=models.CharField(max_length=16, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=16, null=True, verbose_name='手机号码'),
        ),
    ]
