# Generated by Django 2.2.3 on 2019-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190728_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(default='这个人很懒什么都没有留下', max_length=255, verbose_name='个性签名'),
        ),
    ]
