# Generated by Django 2.2.3 on 2019-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190730_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_keep_play',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否是陪玩'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_singer',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否是卖唱'),
        ),
    ]
