# Generated by Django 2.2.3 on 2019-07-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190731_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_keep_play',
        ),
    ]
