# Generated by Django 2.2.3 on 2019-08-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userinfo_is_keep_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/static/image/default.png', null=True, upload_to='media/head_img/', verbose_name='头像'),
        ),
    ]
