# Generated by Django 2.2.3 on 2019-08-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190801_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/static/image/default.png', null=True, upload_to='head_img/', verbose_name='头像'),
        ),
    ]
