# Generated by Django 2.2.3 on 2019-07-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PalyerInfo9',
        ),
    ]
