# Generated by Django 2.2.3 on 2019-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_delete_palyerinfo9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='is_humor',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], verbose_name='幽默与否'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='is_skill',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='技术与否'),
            preserve_default=False,
        ),
    ]
