# Generated by Django 2.2.3 on 2019-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20190731_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinfo',
            options={'verbose_name_plural': '陪打表'},
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='is_working',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='待业与否'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='work_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='接单数'),
        ),
    ]
