# Generated by Django 2.2.3 on 2019-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20190731_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='is_working',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], default=1, verbose_name='待业与否'),
        ),
    ]
