# Generated by Django 2.2.3 on 2019-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20190731_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='is_keep_play',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否是陪玩'),
        ),
    ]
