# Generated by Django 2.2.3 on 2019-08-01 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0008_auto_20190801_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('content', models.CharField(max_length=64, verbose_name='评论内容')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='player.PlayComment', verbose_name='回复哪条评论')),
                ('player', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='player.PlayerInfo', verbose_name='用户表')),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户表')),
            ],
        ),
    ]
