# Generated by Django 2.2.3 on 2019-08-01 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0009_playcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayComment',
            new_name='PlayerComment',
        ),
    ]
